export const categories = [
  { value: "all", label: "All" },
  { value: "entertainment", label: "Entertainment" },
  { value: "music", label: "Music" },
  { value: "productivity", label: "Productivity" },
  { value: "cloud", label: "Cloud" },
  { value: "gaming", label: "Gaming" },
  { value: "education", label: "Education" },
  { value: "fitness", label: "Fitness" },
  { value: "news", label: "News" },
  { value: "finance", label: "Finance" },
  { value: "other", label: "Other" },
]

export const currencies = [
  { value: "USD", label: "$ USD" },
  { value: "EUR", label: "€ EUR" },
  { value: "GBP", label: "£ GBP" },
  { value: "JPY", label: "¥ JPY" },
  { value: "AUD", label: "A$ AUD" },
  { value: "CAD", label: "C$ CAD" },
  { value: "INR", label: "₹ INR" },
  { value: "KRW", label: "₩ KRW" },
  { value: "SGD", label: "S$ SGD" },
  { value: "BRL", label: "R$ BRL" },
  { value: "MXN", label: "$ MXN" },
  { value: "THB", label: "฿ THB" },
  { value: "IDR", label: "Rp IDR" },
  { value: "MYR", label: "RM MYR" },
  { value: "PHP", label: "₱ PHP" },
  { value: "VND", label: "₫ VND" },
  { value: "NZD", label: "NZ$ NZD" },
  { value: "SEK", label: "kr SEK" },
  { value: "NOK", label: "kr NOK" },
  { value: "DKK", label: "kr DKK" },
  { value: "PLN", label: "zł PLN" },
  { value: "CZK", label: "Kč CZK" },
  { value: "HUF", label: "Ft HUF" },
  { value: "TRY", label: "₺ TRY" },
  { value: "ZAR", label: "R ZAR" },
  { value: "AED", label: "د.إ AED" },
  { value: "SAR", label: "﷼ SAR" },
  { value: "TWD", label: "NT$ TWD" },
]

export const currencySymbols: Record<string, string> = {
  USD: "$",
  EUR: "€",
  GBP: "£",
  JPY: "¥",
  AUD: "A$",
  CAD: "C$",
  INR: "₹",
  KRW: "₩",
  SGD: "S$",
  BRL: "R$",
  MXN: "$",
  THB: "฿",
  IDR: "Rp",
  MYR: "RM",
  PHP: "₱",
  VND: "₫",
  NZD: "NZ$",
  SEK: "kr",
  NOK: "kr",
  DKK: "kr",
  PLN: "zł",
  CZK: "Kč",
  HUF: "Ft",
  TRY: "₺",
  ZAR: "R",
  AED: "د.إ",
  SAR: "﷼",
  TWD: "NT$",
}

export const categoryColors: Record<string, string> = {
  entertainment: "#E50914",
  music: "#1DB954",
  productivity: "#0078D4",
  cloud: "#5ac8fa",
  gaming: "#107C10",
  education: "#FF9500",
  fitness: "#FF2D55",
  news: "#AF52DE",
  finance: "#34C759",
  other: "#8E8E93",
}

export const billingCycles = [
  { value: "daily", label: "Daily" },
  { value: "weekly", label: "Weekly" },
  { value: "monthly", label: "Monthly" },
  { value: "quarterly", label: "3 Months" },
  { value: "semi-annual", label: "6 Months" },
  { value: "yearly", label: "Yearly" },
  { value: "none", label: "No Cycle" },
]

export const iconList = [
  "Tv",
  "Music",
  "Film",
  "Clapperboard",
  "Play",
  "Camera",
  "Headphones",
  "Radio",
  "Mic",
  "Podcast",
  "BookOpen",
  "GraduationCap",
  "Palette",
  "Laptop",
  "Monitor",
  "Cloud",
  "Shield",
  "Robot",
  "Brain",
  "Rocket",
  "Zap",
  "Flame",
  "Star",
  "Heart",
  "Gem",
  "Crown",
  "Trophy",
  "Puzzle",
  "Dice",
  "Paintbrush",
  "WandSparkles",
  "Dumbbell",
  "HeartPulse",
  "Footprints",
  "Bicycle",
  "Flower2",
  "Moon",
  "Sun",
  "CloudSun",
  "Globe",
  "Compass",
  "MapPin",
  "Wallet",
  "CreditCard",
  "Receipt",
  "BarChart3",
  "Briefcase",
  "Building2",
  "Store",
  "ShoppingCart",
  "Gift",
  "Tag",
  "Percent",
  "Truck",
  "Plane",
  "Train",
  "Car",
  "Hotel",
  "Umbrella",
  "Map",
  "Passport",
  "Phone",
  "Mail",
  "MessageCircle",
  "Users",
  "Child",
  "Cat",
  "Dog",
  "PawPrint",
  "Sprout",
  "TreePine",
  "Leaf",
  "Waves",
  "Snowflake",
  "Wind",
  "Gamepad",
  "Gamepad2",
  "Apple",
  "Box",
  "Youtube",
  "RefreshCw",
  "Download",
  "Upload",
  "Bell",
  "Settings",
  "Info",
  "Search",
  "Plus",
  "X",
  "Check",
  "MoreHorizontal",
  "MoreVertical",
  "ArrowLeft",
  "ArrowRight",
  "ChevronLeft",
  "ChevronRight",
  "Trash2",
  "Pencil",
  "Copy",
  "Pause",
  "Play",
  "Calendar",
  "CalendarDays",
  "Clock",
  "Timer",
  "Hourglass",
  "Sparkles",
  "Eye",
  "EyeOff",
  "Lock",
  "Unlock",
  "Key",
  "Fingerprint",
  "Scan",
  "QrCode",
  "Link",
  "ExternalLink",
  "Share2",
  "FileText",
  "File",
  "Folder",
  "Image",
  "Video",
  "Music2",
  "Mic2",
  "Volume2",
  "VolumeX",
  "Wifi",
  "Bluetooth",
  "Battery",
  "BatteryFull",
  "Lightbulb",
  "Droplets",
  "Mountain",
  "Sunrise",
  "Sunset",
  "MoonStar",
  "Sparkle",
  "Feather",
]

export function getSymbol(currency: string): string {
  return currencySymbols[currency] || "$"
}

export function calculateMonthlyTotal(
  subs: Array<{ price: number; cycle: string }>
): number {
  return subs.reduce((sum, s) => {
    const cycle = (s.cycle || "monthly").toLowerCase()
    if (cycle === "monthly") return sum + s.price
    if (cycle === "quarterly") return sum + s.price / 3
    if (cycle === "semi-annual") return sum + s.price / 6
    if (cycle === "yearly") return sum + s.price / 12
    if (cycle === "weekly") return sum + s.price * 4.33
    if (cycle === "daily") return sum + s.price * 30
    if (cycle === "none") return sum
    return sum + s.price
  }, 0)
}

export function formatCurrency(amount: number, currency: string): string {
  const symbol = getSymbol(currency)
  return `${symbol}${amount.toFixed(2)}`
}
