export const categories = [
  { value: "all", label: "All" },
  { value: "entertainment", label: "Entertainment" },
  { value: "music", label: "Music" },
  { value: "productivity", label: "Productivity" },
  { value: "cloud", label: "Cloud" },
  { value: "gaming", label: "Gaming" },
  { value: "education", label: "Education" },
  { value: "fitness", label: "Fitness" },
  { value: "news", label: "News" },
  { value: "finance", label: "Finance" },
  { value: "other", label: "Other" },
]

export const currencies = [
  { value: "USD", label: "$ USD" },
  { value: "EUR", label: "\u20ac EUR" },
  { value: "GBP", label: "\u00a3 GBP" },
  { value: "JPY", label: "\u00a5 JPY" },
  { value: "AUD", label: "A$ AUD" },
  { value: "CAD", label: "C$ CAD" },
  { value: "INR", label: "\u20b9 INR" },
  { value: "KRW", label: "\u20a9 KRW" },
  { value: "SGD", label: "S$ SGD" },
  { value: "BRL", label: "R$ BRL" },
  { value: "MXN", label: "$ MXN" },
  { value: "THB", label: "\u0e3f THB" },
  { value: "IDR", label: "Rp IDR" },
  { value: "MYR", label: "RM MYR" },
  { value: "PHP", label: "\u20b1 PHP" },
  { value: "VND", label: "\u20ab VND" },
  { value: "NZD", label: "NZ$ NZD" },
  { value: "SEK", label: "kr SEK" },
  { value: "NOK", label: "kr NOK" },
  { value: "DKK", label: "kr DKK" },
  { value: "PLN", label: "z\u0142 PLN" },
  { value: "CZK", label: "K\u010d CZK" },
  { value: "HUF", label: "Ft HUF" },
  { value: "TRY", label: "\u20ba TRY" },
  { value: "ZAR", label: "R ZAR" },
  { value: "AED", label: "د.إ AED" },
  { value: "SAR", label: "\ufd5e SAR" },
  { value: "TWD", label: "NT$ TWD" },
]

export const currencySymbols: Record<string, string> = {
  USD: "$",
  EUR: "\u20ac",
  GBP: "\u00a3",
  JPY: "\u00a5",
  AUD: "A$",
  CAD: "C$",
  INR: "\u20b9",
  KRW: "\u20a9",
  SGD: "S$",
  BRL: "R$",
  MXN: "$",
  THB: "\u0e3f",
  IDR: "Rp",
  MYR: "RM",
  PHP: "\u20b1",
  VND: "\u20ab",
  NZD: "NZ$",
  SEK: "kr",
  NOK: "kr",
  DKK: "kr",
  PLN: "z\u0142",
  CZK: "K\u010d",
  HUF: "Ft",
  TRY: "\u20ba",
  ZAR: "R",
  AED: "د.إ",
  SAR: "\ufd5e",
  TWD: "NT$",
}

export const categoryColors: Record<string, string> = {
  entertainment: "#E50914",
  music: "#1DB954",
  productivity: "#0078D4",
  cloud: "#5ac8fa",
  gaming: "#107C10",
  education: "#FF9500",
  fitness: "#FF2D55",
  news: "#AF52DE",
  finance: "#34C759",
  other: "#8E8E93",
}

export const billingCycles = [
  { value: "daily", label: "Daily" },
  { value: "weekly", label: "Weekly" },
  { value: "monthly", label: "Monthly" },
  { value: "yearly", label: "Yearly" },
]

export const iconList = [
  "Tv",
  "Music",
  "Film",
  "Clapperboard",
  "Play",
  "Camera",
  "Headphones",
  "Radio",
  "Mic",
  "Podcast",
  "BookOpen",
  "GraduationCap",
  "Palette",
  "Laptop",
  "Monitor",
  "Cloud",
  "Shield",
  "Robot",
  "Brain",
  "Rocket",
  "Zap",
  "Flame",
  "Star",
  "Heart",
  "Gem",
  "Crown",
  "Trophy",
  "Puzzle",
  "Dice",
  "Paintbrush",
  "WandSparkles",
  "Dumbbell",
  "HeartPulse",
  "Footprints",
  "Bicycle",
  "Flower2",
  "Moon",
  "Sun",
  "CloudSun",
  "Globe",
  "Compass",
  "MapPin",
  "Wallet",
  "CreditCard",
  "Receipt",
  "BarChart3",
  "Briefcase",
  "Building2",
  "Store",
  "ShoppingCart",
  "Gift",
  "Tag",
  "Percent",
  "Truck",
  "Plane",
  "Train",
  "Car",
  "Hotel",
  "Umbrella",
  "Map",
  "Passport",
  "Phone",
  "Mail",
  "MessageCircle",
  "Users",
  "Child",
  "Cat",
  "Dog",
  "PawPrint",
  "Sprout",
  "TreePine",
  "Leaf",
  "Waves",
  "Snowflake",
  "Wind",
  "Gamepad",
  "Gamepad2",
  "Apple",
  "Box",
  "Youtube",
  "RefreshCw",
  "Download",
  "Upload",
  "Bell",
  "Settings",
  "Info",
  "Search",
  "Plus",
  "X",
  "Check",
  "MoreHorizontal",
  "MoreVertical",
  "ArrowLeft",
  "ArrowRight",
  "ChevronLeft",
  "ChevronRight",
  "Trash2",
  "Pencil",
  "Copy",
  "Pause",
  "Play",
  "Calendar",
  "CalendarDays",
  "Clock",
  "Timer",
  "Hourglass",
  "Sparkles",
  "Eye",
  "EyeOff",
  "Lock",
  "Unlock",
  "Key",
  "Fingerprint",
  "Scan",
  "QrCode",
  "Link",
  "ExternalLink",
  "Share2",
  "Download",
  "Upload",
  "FileText",
  "File",
  "Folder",
  "Image",
  "Video",
  "Music2",
  "Mic2",
  "Volume2",
  "VolumeX",
  "Wifi",
  "Bluetooth",
  "Battery",
  "BatteryFull",
  "Lightbulb",
  "Flame",
  "Droplets",
  "Mountain",
  "Sunrise",
  "Sunset",
  "MoonStar",
  "Sparkle",
  "Feather",
]

export function getSymbol(currency: string): string {
  return currencySymbols[currency] || "$"
}

export function calculateMonthlyTotal(
  subs: Array<{ price: number; cycle: string }>
): number {
  return subs.reduce((sum, s) => {
    if (s.cycle === "monthly") return sum + s.price
    if (s.cycle === "yearly") return sum + s.price / 12
    if (s.cycle === "weekly") return sum + s.price * 4.33
    if (s.cycle === "daily") return sum + s.price * 30
    return sum + s.price
  }, 0)
}

export function formatCurrency(amount: number, currency: string): string {
  const symbol = getSymbol(currency)
  return `${symbol}${amount.toFixed(2)}`
}
