import React, { memo } from "react"
import { Image } from "expo-image"
import {
  Activity,
  Apple,
  ArrowLeft,
  AtSign,
  Award,
  Banknote,
  BarChart3,
  Beer,
  Bell,
  Bike,
  BookOpen,
  Bot,
  Box,
  Brain,
  Briefcase,
  Building2,
  Cake,
  Calendar,
  Camera,
  Car,
  Check,
  CheckCircle,
  Clapperboard,
  Clock,
  Cloud,
  CloudDownload,
  CloudUpload,
  Code,
  Coffee,
  Coins,
  CreditCard,
  Crosshair,
  Database,
  Dice5,
  Disc,
  DollarSign,
  Dumbbell,
  Feather,
  FileCode,
  FileText,
  Film,
  Flame,
  Flower2,
  Folder,
  FolderGit2,
  Footprints,
  Gamepad,
  Gamepad2,
  Gift,
  GitBranch,
  Globe,
  GraduationCap,
  Guitar,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HeartPulse,
  Inbox,
  Joystick,
  Landmark,
  Laptop,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  MessagesSquare,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  Mountain,
  Music,
  Music2,
  Package,
  Paintbrush,
  Palette,
  PenTool,
  Percent,
  Phone,
  PhoneCall,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Play,
  Podcast,
  Plus,
  Popcorn,
  Presentation,
  Puzzle,
  Radio,
  Receipt,
  Rocket,
  Search,
  Send,
  Server,
  Share2,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Speech,
  Star,
  Stethoscope,
  StickyNote,
  Store,
  Sun,
  Sword,
  Tag,
  Terminal,
  ThumbsUp,
  Ticket,
  TrendingUp,
  Trophy,
  Tv,
  Tv2,
  Upload,
  UserCheck,
  UserPlus,
  Users,
  Utensils,
  Video,
  Volume,
  Volume2,
  Wallet,
  Wand2,
  WandSparkles,
  Waves,
  Wifi,
  Wine,
  X,
  Zap,
  LucideIcon,
} from "lucide-react-native"

const STATIC_ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  apple: Apple,
  "arrow-left": ArrowLeft,
  "at-sign": AtSign,
  award: Award,
  banknote: Banknote,
  "bar-chart-3": BarChart3,
  beer: Beer,
  bell: Bell,
  bicycle: Bike,
  bike: Bike,
  "book-open": BookOpen,
  bot: Bot,
  box: Box,
  brain: Brain,
  briefcase: Briefcase,
  "building-2": Building2,
  cake: Cake,
  calendar: Calendar,
  camera: Camera,
  car: Car,
  check: Check,
  "check-circle": CheckCircle,
  clapperboard: Clapperboard,
  clock: Clock,
  cloud: Cloud,
  "cloud-download": CloudDownload,
  "cloud-upload": CloudUpload,
  code: Code,
  coffee: Coffee,
  coins: Coins,
  "credit-card": CreditCard,
  crosshair: Crosshair,
  database: Database,
  dice5: Dice5,
  disc: Disc,
  "dollar-sign": DollarSign,
  dumbbell: Dumbbell,
  feather: Feather,
  "file-code": FileCode,
  "file-text": FileText,
  film: Film,
  flame: Flame,
  flower2: Flower2,
  folder: Folder,
  "folder-git-2": FolderGit2,
  footprints: Footprints,
  gamepad: Gamepad,
  gamepad2: Gamepad2,
  gift: Gift,
  "git-branch": GitBranch,
  globe: Globe,
  "graduation-cap": GraduationCap,
  guitar: Guitar,
  "hard-drive": HardDrive,
  hash: Hash,
  headphones: Headphones,
  heart: Heart,
  "heart-pulse": HeartPulse,
  inbox: Inbox,
  joystick: Joystick,
  landmark: Landmark,
  laptop: Laptop,
  lock: Lock,
  mail: Mail,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  "messages-square": MessagesSquare,
  "message-square": MessageSquare,
  mic: Mic,
  monitor: Monitor,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  music2: Music2,
  package: Package,
  paintbrush: Paintbrush,
  palette: Palette,
  "pen-tool": PenTool,
  percent: Percent,
  phone: Phone,
  "phone-call": PhoneCall,
  "piggy-bank": PiggyBank,
  pill: Pill,
  pizza: Pizza,
  plane: Plane,
  play: Play,
  podcast: Podcast,
  plus: Plus,
  popcorn: Popcorn,
  presentation: Presentation,
  puzzle: Puzzle,
  radio: Radio,
  receipt: Receipt,
  robot: Bot,
  rocket: Rocket,
  search: Search,
  send: Send,
  server: Server,
  "share-2": Share2,
  shield: Shield,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  sparkles: Sparkles,
  speech: Speech,
  star: Star,
  stethoscope: Stethoscope,
  "sticky-note": StickyNote,
  store: Store,
  sun: Sun,
  sword: Sword,
  tag: Tag,
  terminal: Terminal,
  "thumbs-up": ThumbsUp,
  ticket: Ticket,
  "trending-up": TrendingUp,
  trophy: Trophy,
  tv: Tv,
  tv2: Tv2,
  upload: Upload,
  "user-check": UserCheck,
  "user-plus": UserPlus,
  users: Users,
  utensils: Utensils,
  video: Video,
  volume: Volume,
  "volume-2": Volume2,
  wallet: Wallet,
  wand2: Wand2,
  "wand-sparkles": WandSparkles,
  waves: Waves,
  wifi: Wifi,
  wine: Wine,
  x: X,
  youtube: Play,
  zap: Zap,
}

function isImageUrl(url: string): boolean {
  if (!url) return false
  const trimmed = url.trim()
  return (
    trimmed.startsWith("http://") ||
    trimmed.startsWith("https://") ||
    trimmed.startsWith("data:image/") ||
    trimmed.startsWith("blob:")
  )
}

function normalizeIconName(name: string): string {
  if (!name) return "receipt"
  return name
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[\s_]+/g, "-")
    .toLowerCase()
}

export interface DynamicIconProps {
  name: string
  size?: number
  color?: string
}

export const DynamicIcon = memo(function DynamicIcon({
  name,
  size = 20,
  color = "#ffffff",
}: DynamicIconProps) {
  if (name && isImageUrl(name)) {
    return (
      <Image
        source={{ uri: name }}
        style={{ width: size, height: size, borderRadius: 4 }}
        contentFit="contain"
      />
    )
  }

  const kebab = normalizeIconName(name)
  const Component = STATIC_ICONS[kebab] || Receipt

  return <Component size={size} color={color} />
})
