export const currencies = [
  { value: "USD", label: "$ USD" },
  { value: "EUR", label: "€ EUR" },
  { value: "GBP", label: "£ GBP" },
  { value: "JPY", label: "¥ JPY" },
  { value: "AUD", label: "A$ AUD" },
  { value: "CAD", label: "C$ CAD" },
  { value: "INR", label: "₹ INR" },
  { value: "KRW", label: "₩ KRW" },
  { value: "SGD", label: "S$ SGD" },
  { value: "BRL", label: "R$ BRL" },
  { value: "MXN", label: "$ MXN" },
  { value: "THB", label: "฿ THB" },
  { value: "IDR", label: "Rp IDR" },
  { value: "MYR", label: "RM MYR" },
  { value: "PHP", label: "₱ PHP" },
  { value: "VND", label: "₫ VND" },
  { value: "NZD", label: "NZ$ NZD" },
  { value: "SEK", label: "kr SEK" },
  { value: "NOK", label: "kr NOK" },
  { value: "DKK", label: "kr DKK" },
  { value: "PLN", label: "zł PLN" },
  { value: "CZK", label: "Kč CZK" },
  { value: "HUF", label: "Ft HUF" },
  { value: "TRY", label: "₺ TRY" },
  { value: "ZAR", label: "R ZAR" },
  { value: "AED", label: "د.إ AED" },
  { value: "SAR", label: "﷼ SAR" },
  { value: "TWD", label: "NT$ TWD" },
]

export const currencySymbols: Record<string, string> = {
  USD: "$",
  EUR: "€",
  GBP: "£",
  JPY: "¥",
  AUD: "A$",
  CAD: "C$",
  INR: "₹",
  KRW: "₩",
  SGD: "S$",
  BRL: "R$",
  MXN: "$",
  THB: "฿",
  IDR: "Rp",
  MYR: "RM",
  PHP: "₱",
  VND: "₫",
  NZD: "NZ$",
  SEK: "kr",
  NOK: "kr",
  DKK: "kr",
  PLN: "zł",
  CZK: "Kč",
  HUF: "Ft",
  TRY: "₺",
  ZAR: "R",
  AED: "د.إ",
  SAR: "﷼",
  TWD: "NT$",
}

export function getSymbol(currency: string): string {
  return currencySymbols[currency] || "$"
}
